export const players = [
    {
        name: 'Mbappe',
        position: 'ST',
        rating: 90,
        image: '/Kylian-Mbappe-a0b6a5c-removebg-preview.png',
        pace: 90,
        shooting: 90,
        passing: 90,
        dribbling: 90,
        defending: 90,
        physicality: 90,
        weak_foot: 90,
        skill_moves: 90,
        position_ability: ['ST', 'CF', 'RW', 'LW'],
        card:'RTTK'
    },
    {
        name: 'Bellignham',
        position: 'CM',
        rating: 90,
        image: '/Jude-Bellingham-c629a24-removebg-preview.png',
        pace: 0,
        shooting: 0,
        passing: 0,
        dribbling: 0,
        defending: 0,
        physicality: 0,
        weak_foot: 0,
        skill_moves: 0,
        position_ability: ['CM', 'CDM', 'CAM'],
         card:'FUTB'
    },
    {
        name: 'Messi',
        position: 'LW',
        rating: 90,
        image: '/lionel-messi_imago1019567000h-removebg-preview.png',
        pace: 0,
        shooting: 0,
        passing: 0,
        dribbling: 0,
        defending: 0,
        physicality: 0,
        weak_foot: 0,
        skill_moves: 0,
        position_ability: ['RW', 'CF', 'CAM'],
         card:'FB'
    },
    {
        name: 'Leao',
        position: 'RW',
        rating: 90,
        image: '/leao.png',
        pace: 0,
        shooting: 0,
        passing: 0,
        dribbling: 0,
        defending: 0,
        physicality: 0,
        weak_foot: 0,
        skill_moves: 0,
        position_ability: ['ST', 'LW', 'RW'],
         card:'RTTK'
    },
    {
        name: 'Neymar',
        position: 'RW',
        rating: 90,
        image: '/neymar.png',
        pace: 0,
        shooting: 0,
        passing: 0,
        dribbling: 0,
        defending: 0,
        physicality: 0,
        weak_foot: 0,
        skill_moves: 0,
        position_ability: ['ST', 'LW', 'RW'],
        card:'RTTK'

    },
    {
        name: 'Palmer',
        position: 'CM',
        rating: 90,
        image: '/Cole-Palmer-Chelsea-1024x576-removebg-preview.png',
        pace: 0,
        shooting: 0,
        passing: 0,
        dribbling: 0,
        defending: 0,
        physicality: 0,
        weak_foot: 0,
        skill_moves: 0,
        position_ability: ['ST', 'CAM', 'RW'],
         card:'FUTB'
    }
]
