export const players = [
    {
        name: 'Mbappe',
        position: 'ST',
        rating: 90,
        image: '/mbappe.webp',
        pace: 90,
        shooting: 90,
        passing: 90,
        dribbling: 90,
        defending: 90,
        physicality: 90,
        weak_foot: 5,
        skill_moves: 5,
        position_ability: ['ST', 'CF', 'RW', 'LW'],
        card:'RTTK'
    },
    {
        name: 'Bellignham',
        position: 'CM',
        rating: 90,
        image: '/jude.webp',
        pace: 82,
        shooting: 81,
        passing: 87,
        dribbling: 88,
        defending: 76,
        physicality: 84,
        weak_foot: 4,
        skill_moves: 4,
        position_ability: ['CM', 'CDM', 'CAM'],
        card:'FUTB'
    },
    {
        name: 'Messi',
        position: 'LW',
        rating: 90,
        image: '/messi.webp',
        pace: 83,
        shooting: 91,
        passing: 93,
        dribbling: 95,
        defending: 36,
        physicality: 69,
        weak_foot: 4,
        skill_moves: 4,
        position_ability: ['RW', 'CF', 'CAM'],
        card:'FB'
    },
    {
        name: 'Leao',
        position: 'RW',
        rating: 90,
        image: '/leao.webp',
        pace: 91,
        shooting: 83,
        passing: 79,
        dribbling: 87,
        defending: 31,
        physicality: 83,
        weak_foot: 3,
        skill_moves: 4,
        position_ability: ['ST', 'LW', 'RW'],
        card:'RTTK'
    },
    {
        name: 'Neymar',
        position: 'RW',
        rating: 90,
        image: '/neymar.webp',
        pace: 86,
        shooting: 87,
        passing: 86,
        dribbling: 93,
        defending: 34,
        physicality: 71,
        weak_foot: 5,
        skill_moves: 5,
        position_ability: ['ST', 'LW', 'RW'],
        card:'RTTK'
    },
    {
        name: 'Palmer',
        position: 'CM',
        rating: 90,
        image: '/palmer.webp',
        pace: 79,
        shooting: 84,
        passing: 83,
        dribbling: 85,
        defending: 52,
        physicality: 76,
        weak_foot: 4,
        skill_moves: 3,
        position_ability: ['ST', 'CAM', 'RW'],
        card:'FUTB'
    }
]
